//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskTopShop.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommingUp", Namespace="http://schemas.datacontract.org/2004/07/ServiceCentralStock")]
    [System.SerializableAttribute()]
    public partial class CommingUp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DMYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VonderCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DMY {
            get {
                return this.DMYField;
            }
            set {
                if ((object.ReferenceEquals(this.DMYField, value) != true)) {
                    this.DMYField = value;
                    this.RaisePropertyChanged("DMY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InStock {
            get {
                return this.InStockField;
            }
            set {
                if ((object.ReferenceEquals(this.InStockField, value) != true)) {
                    this.InStockField = value;
                    this.RaisePropertyChanged("InStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFirm {
            get {
                return this.NameFirmField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFirmField, value) != true)) {
                    this.NameFirmField = value;
                    this.RaisePropertyChanged("NameFirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameModel {
            get {
                return this.NameModelField;
            }
            set {
                if ((object.ReferenceEquals(this.NameModelField, value) != true)) {
                    this.NameModelField = value;
                    this.RaisePropertyChanged("NameModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VonderCode {
            get {
                return this.VonderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VonderCodeField, value) != true)) {
                    this.VonderCodeField = value;
                    this.RaisePropertyChanged("VonderCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sending", Namespace="http://schemas.datacontract.org/2004/07/ServiceCentralStock")]
    [System.SerializableAttribute()]
    public partial class Sending : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DolgotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameFirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShirotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOfSendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VonderCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dolgota {
            get {
                return this.DolgotaField;
            }
            set {
                if ((object.ReferenceEquals(this.DolgotaField, value) != true)) {
                    this.DolgotaField = value;
                    this.RaisePropertyChanged("Dolgota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameFirm {
            get {
                return this.NameFirmField;
            }
            set {
                if ((object.ReferenceEquals(this.NameFirmField, value) != true)) {
                    this.NameFirmField = value;
                    this.RaisePropertyChanged("NameFirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameModel {
            get {
                return this.NameModelField;
            }
            set {
                if ((object.ReferenceEquals(this.NameModelField, value) != true)) {
                    this.NameModelField = value;
                    this.RaisePropertyChanged("NameModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shirota {
            get {
                return this.ShirotaField;
            }
            set {
                if ((object.ReferenceEquals(this.ShirotaField, value) != true)) {
                    this.ShirotaField = value;
                    this.RaisePropertyChanged("Shirota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOfSend {
            get {
                return this.TimeOfSendField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOfSendField, value) != true)) {
                    this.TimeOfSendField = value;
                    this.RaisePropertyChanged("TimeOfSend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VonderCode {
            get {
                return this.VonderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VonderCodeField, value) != true)) {
                    this.VonderCodeField = value;
                    this.RaisePropertyChanged("VonderCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdressesShops", Namespace="http://schemas.datacontract.org/2004/07/ServiceCentralStock")]
    [System.SerializableAttribute()]
    public partial class AdressesShops : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DolgotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShirotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dolgota {
            get {
                return this.DolgotaField;
            }
            set {
                if ((object.ReferenceEquals(this.DolgotaField, value) != true)) {
                    this.DolgotaField = value;
                    this.RaisePropertyChanged("Dolgota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Shirota {
            get {
                return this.ShirotaField;
            }
            set {
                if ((object.ReferenceEquals(this.ShirotaField, value) != true)) {
                    this.ShirotaField = value;
                    this.RaisePropertyChanged("Shirota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiceCentralStock")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Comming_Phones", ReplyAction="http://tempuri.org/IService1/Select_Comming_PhonesResponse")]
        DeskTopShop.ServiceReference1.CommingUp[] Select_Comming_Phones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Comming_Phones", ReplyAction="http://tempuri.org/IService1/Select_Comming_PhonesResponse")]
        System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CommingUp[]> Select_Comming_PhonesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Comming_Phones_one", ReplyAction="http://tempuri.org/IService1/Select_Comming_Phones_oneResponse")]
        DeskTopShop.ServiceReference1.CommingUp[] Select_Comming_Phones_one(string VonderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Comming_Phones_one", ReplyAction="http://tempuri.org/IService1/Select_Comming_Phones_oneResponse")]
        System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CommingUp[]> Select_Comming_Phones_oneAsync(string VonderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_Comming", ReplyAction="http://tempuri.org/IService1/Insert_CommingResponse")]
        void Insert_Comming(DeskTopShop.ServiceReference1.CommingUp r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_Comming", ReplyAction="http://tempuri.org/IService1/Insert_CommingResponse")]
        System.Threading.Tasks.Task Insert_CommingAsync(DeskTopShop.ServiceReference1.CommingUp r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Comming", ReplyAction="http://tempuri.org/IService1/Update_CommingResponse")]
        void Update_Comming(string VonderCode, string NameFirm, DeskTopShop.ServiceReference1.CommingUp r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Comming", ReplyAction="http://tempuri.org/IService1/Update_CommingResponse")]
        System.Threading.Tasks.Task Update_CommingAsync(string VonderCode, string NameFirm, DeskTopShop.ServiceReference1.CommingUp r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Comming", ReplyAction="http://tempuri.org/IService1/Delete_CommingResponse")]
        void Delete_Comming(string VonderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_Comming", ReplyAction="http://tempuri.org/IService1/Delete_CommingResponse")]
        System.Threading.Tasks.Task Delete_CommingAsync(string VonderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Sending", ReplyAction="http://tempuri.org/IService1/Update_SendingResponse")]
        void Update_Sending(string VonderCode, string Address, string Status, int id, DeskTopShop.ServiceReference1.Sending s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update_Sending", ReplyAction="http://tempuri.org/IService1/Update_SendingResponse")]
        System.Threading.Tasks.Task Update_SendingAsync(string VonderCode, string Address, string Status, int id, DeskTopShop.ServiceReference1.Sending s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_AdressesShops", ReplyAction="http://tempuri.org/IService1/Select_AdressesShopsResponse")]
        DeskTopShop.ServiceReference1.AdressesShops[] Select_AdressesShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_AdressesShops", ReplyAction="http://tempuri.org/IService1/Select_AdressesShopsResponse")]
        System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.AdressesShops[]> Select_AdressesShopsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_SendingPhone", ReplyAction="http://tempuri.org/IService1/Insert_SendingPhoneResponse")]
        void Insert_SendingPhone(DeskTopShop.ServiceReference1.Sending s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_SendingPhone", ReplyAction="http://tempuri.org/IService1/Insert_SendingPhoneResponse")]
        System.Threading.Tasks.Task Insert_SendingPhoneAsync(DeskTopShop.ServiceReference1.Sending s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Sending", ReplyAction="http://tempuri.org/IService1/Select_SendingResponse")]
        DeskTopShop.ServiceReference1.Sending[] Select_Sending();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select_Sending", ReplyAction="http://tempuri.org/IService1/Select_SendingResponse")]
        System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.Sending[]> Select_SendingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_AddressNew", ReplyAction="http://tempuri.org/IService1/Insert_AddressNewResponse")]
        void Insert_AddressNew(DeskTopShop.ServiceReference1.AdressesShops r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert_AddressNew", ReplyAction="http://tempuri.org/IService1/Insert_AddressNewResponse")]
        System.Threading.Tasks.Task Insert_AddressNewAsync(DeskTopShop.ServiceReference1.AdressesShops r);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        DeskTopShop.ServiceReference1.CompositeType GetDataUsingDataContract(DeskTopShop.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(DeskTopShop.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : DeskTopShop.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<DeskTopShop.ServiceReference1.IService1>, DeskTopShop.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public DeskTopShop.ServiceReference1.CommingUp[] Select_Comming_Phones() {
            return base.Channel.Select_Comming_Phones();
        }
        
        public System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CommingUp[]> Select_Comming_PhonesAsync() {
            return base.Channel.Select_Comming_PhonesAsync();
        }
        
        public DeskTopShop.ServiceReference1.CommingUp[] Select_Comming_Phones_one(string VonderCode) {
            return base.Channel.Select_Comming_Phones_one(VonderCode);
        }
        
        public System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CommingUp[]> Select_Comming_Phones_oneAsync(string VonderCode) {
            return base.Channel.Select_Comming_Phones_oneAsync(VonderCode);
        }
        
        public void Insert_Comming(DeskTopShop.ServiceReference1.CommingUp r) {
            base.Channel.Insert_Comming(r);
        }
        
        public System.Threading.Tasks.Task Insert_CommingAsync(DeskTopShop.ServiceReference1.CommingUp r) {
            return base.Channel.Insert_CommingAsync(r);
        }
        
        public void Update_Comming(string VonderCode, string NameFirm, DeskTopShop.ServiceReference1.CommingUp r) {
            base.Channel.Update_Comming(VonderCode, NameFirm, r);
        }
        
        public System.Threading.Tasks.Task Update_CommingAsync(string VonderCode, string NameFirm, DeskTopShop.ServiceReference1.CommingUp r) {
            return base.Channel.Update_CommingAsync(VonderCode, NameFirm, r);
        }
        
        public void Delete_Comming(string VonderCode) {
            base.Channel.Delete_Comming(VonderCode);
        }
        
        public System.Threading.Tasks.Task Delete_CommingAsync(string VonderCode) {
            return base.Channel.Delete_CommingAsync(VonderCode);
        }
        
        public void Update_Sending(string VonderCode, string Address, string Status, int id, DeskTopShop.ServiceReference1.Sending s) {
            base.Channel.Update_Sending(VonderCode, Address, Status, id, s);
        }
        
        public System.Threading.Tasks.Task Update_SendingAsync(string VonderCode, string Address, string Status, int id, DeskTopShop.ServiceReference1.Sending s) {
            return base.Channel.Update_SendingAsync(VonderCode, Address, Status, id, s);
        }
        
        public DeskTopShop.ServiceReference1.AdressesShops[] Select_AdressesShops() {
            return base.Channel.Select_AdressesShops();
        }
        
        public System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.AdressesShops[]> Select_AdressesShopsAsync() {
            return base.Channel.Select_AdressesShopsAsync();
        }
        
        public void Insert_SendingPhone(DeskTopShop.ServiceReference1.Sending s) {
            base.Channel.Insert_SendingPhone(s);
        }
        
        public System.Threading.Tasks.Task Insert_SendingPhoneAsync(DeskTopShop.ServiceReference1.Sending s) {
            return base.Channel.Insert_SendingPhoneAsync(s);
        }
        
        public DeskTopShop.ServiceReference1.Sending[] Select_Sending() {
            return base.Channel.Select_Sending();
        }
        
        public System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.Sending[]> Select_SendingAsync() {
            return base.Channel.Select_SendingAsync();
        }
        
        public void Insert_AddressNew(DeskTopShop.ServiceReference1.AdressesShops r) {
            base.Channel.Insert_AddressNew(r);
        }
        
        public System.Threading.Tasks.Task Insert_AddressNewAsync(DeskTopShop.ServiceReference1.AdressesShops r) {
            return base.Channel.Insert_AddressNewAsync(r);
        }
        
        public DeskTopShop.ServiceReference1.CompositeType GetDataUsingDataContract(DeskTopShop.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<DeskTopShop.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(DeskTopShop.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
