//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCentralStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sending
    {
        public int Id { get; set; }
        public string NameFirm { get; set; }
        public string NameModel { get; set; }
        public string VonderCode { get; set; }
        public Nullable<int> Count { get; set; }
        public string Address { get; set; }
        public string Shirota { get; set; }
        public string Dolgota { get; set; }
        public string Status { get; set; }
        public string TimeOfSend { get; set; }
    }
}
