//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaitShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sait
    {
        public int Id { get; set; }
        public string NameFirm { get; set; }
        public string NameModel { get; set; }
        public string VonderCode { get; set; }
        public Nullable<int> Count { get; set; }
        public string InStock { get; set; }
        public string DMY { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Сharacteristic { get; set; }
        public string ImageName { get; set; }
    }
}
