//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskTopShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public string NameFirm { get; set; }
        public string NameModel { get; set; }
        public string VonderCode { get; set; }
        public Nullable<int> Count { get; set; }
        public string InStock { get; set; }
        public string Price { get; set; }
        public string YoarTelephone { get; set; }
        public string Time { get; set; }
        public string Sales { get; set; }
    }
}
